import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LayoutProps } from "./@types/rootLayoutProps";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: LayoutProps) {
  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>{props.children}</body>
    </html>
  );
}
